### ISSUE TITLE
[Infra] 모델 구동환경 구축

### ISSUE THREAD

**Issue by oMFDOo** [oMFDOo/OpenSourceIssue#1]
# 환경 구성
: [Gaussian-Head-Avatar](https://github.com/YuelangX/Gaussian-Head-Avatar)구동을 위한 환경을 구축하고 명시합니다.

<br>

|구성|사양|비고|
|:--:|:--|:--|
|OS|Ubuntu 20.04||
|CPU|AMD EPYC 7V13 64-Core Processor, core(24)||
|GPU|NVIDIA A100||
|RAM|220GiB||
|SSD|프리미엄 SSD LRS 1TB|  - OPS : 5000 <br>  - 처리량(MBps) : 200 <br>  - 디스크 계층 : P30 |

 \* Azure Virtual Machine [Standard NC24ads A100 v4](https://learn.microsoft.com/ko-kr/azure/virtual-machines/sizes/gpu-accelerated/nca100v4-series?tabs=sizebasic#host-specifications)을 이용함

<br><br>

![Image](https://github.com/user-attachments/assets/dea9837e-f0f6-4cab-af09-9f7374790970)

**Comment by oMFDOo** [comment]
### 1) 코드 clone
```js
git clone https://github.com/YuelangX/Gaussian-Head-Avatar.git
```
![Image](https://github.com/user-attachments/assets/05964b15-da47-4f98-93a5-23f043d24af3)


### 2) 가상환경 생성

```js
conda env create -n GaussianHeadAvatar -f environment.yaml
```
![Image](https://github.com/user-attachments/assets/4c4b2e94-b5af-426c-9c14-640a5c63fb44)

### 3) 가상환경 실행 및 [Pytorch3d](https://github.com/facebookresearch/pytorch3d)설치
```js
conda activate GaussianHeadAvatar
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py3
8_cu113_pyt1120/download.html
```
![Image](https://github.com/user-attachments/assets/367872a6-3a74-466b-9883-125c75e0b735)

### 4) kaolin 설치
NVIDIA에서 개발한 3D 딥러닝 연구 및 응용을 위한 PyTorch 라이브러리입니다.  <br>
데이터 처리와 시각화, 3D 딥러닝 모델을 학습 및 3D 데이터셋을 처리할 때 유용한 도구를 제공합니다.  <br>
```js
pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.0_cu113.html
```
![Image](https://github.com/user-attachments/assets/7e6efc00-6c7e-4376-b515-8074220adcb7)


### 5) diff-gaussian-rasterization 및 simple_knn 설치
[gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting)에서 diff-gaussian-rasterization과 simple_knn을 설치합니다.
```js
cd ./gaussian-splatting
# Modify "submodules/diff-gaussian-rasterization/cuda_rasterizer/config.h"
pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn
```
 \+ 추가로 32채널 이미지를 렌더링하려면 "[diff-gaussian-rasterization/cuda_rasterizer/config.h](https://github.com/TimSong412/2D-surfel-gaussian/blob/main/submodules/diff-gaussian-rasterization/cuda_rasterizer/config.h)"에서 "NUM_CHANNELs 3"을 "NUM_CHANELs 32"로 수정하세요.
```python
/*
 * Copyright (C) 2023, Inria
 * GRAPHDECO research group, https://team.inria.fr/graphdeco
 * All rights reserved.
 *
 * This software is free for non-commercial, research and evaluation use 
 * under the terms of the LICENSE.md file.
 *
 * For inquiries contact  george.drettakis@inria.fr
 */

#ifndef CUDA_RASTERIZER_CONFIG_H_INCLUDED
#define CUDA_RASTERIZER_CONFIG_H_INCLUDED

#define NUM_CHANNELS 3 // Default 3, RGB <- 이것을 수정하라는 의미
#define BLOCK_X 16
#define BLOCK_Y 16

#define BLEND_DEPTH

#define Ld
#define far 1000.0f
#define near 0.2f

#define Ln

// define an macro that represent Ld || Ln, used to compute shared values in backwards
#ifdef Ld
#define LdOrLn
#else
#ifdef Ln
#define LdOrLn
#endif
#endif

#endif
```

**Comment by oMFDOo** [comment]
# 5) diff-gaussian-rasterization 및 simple_knn 설치 과정에서의 난관

### [1] 설치 모호성 
![Image](https://github.com/user-attachments/assets/1bc97850-e6f1-4fbd-b89f-cf5d9dd4e2e2)


공식 문서에서의 해당 설치가 의미하는 바가 모호했다. 

<br><br>

### ⏩ 설치 모호성
밑줄친 [diff-gaussian-rasterization/cuda_rasterizer/config.h](https://github.com/TimSong412/2D-surfel-gaussian/blob/main/submodules/diff-gaussian-rasterization/cuda_rasterizer/config.h)와 동일한 파일이 존재하는 repository를 발견하였다.
`pip install submodules/diff-gaussian-rasterization`와 일치하는 경로까지 있어 clone 이후 pip install을 시도하였다.
```bash
git clone https://github.com/TimSong412/2D-surfel-gaussian.git
cd ./2D-surfel-gaussian
pip install submodules/diff-gaussian-rasterization
```
![Image](https://github.com/user-attachments/assets/cfcddadc-1a6f-4d26-bf39-e0d7be7956fa)

<br><br>

### [2] CUDA / PyTorch 버전 불일치 에러 발생
`pip install submodules/diff-gaussian-rasterization`의 결과로 버전 불일치 에러가 발생했다.

![Image](https://github.com/user-attachments/assets/4736037d-2b14-4210-ad5c-e5bf94092256)


### [3] simple-knn 파일 미존재
[해당 이슈](https://github.com/graphdeco-inria/gaussian-splatting/issues/265)를 근거로 [simple-knn 주소](https://github.com/camenduru/simple-knn.git)를 잡아왔다.
```bash
git clone https://github.com/camenduru/simple-knn.git
pip install simple-knn/
```
[2]와 똑같은 이슈 발생
![Image](https://github.com/user-attachments/assets/93b47a74-e3a5-406a-95e5-fac3e6628c10)

**Comment by oMFDOo** [comment]
### CUDA 설치 이후에도 오류 그대로 존재
 : #19 를 근거하여 설치를 마쳤다. 하지만 여전히 같은 오류가 존재하였고, Cmake 파일에 CUDA 경로 지정이 있음을 발견했다.

<br>

### 기존 Cmake.txt
```js
#
# Copyright (C) 2023, Inria
# GRAPHDECO research group, https://team.inria.fr/graphdeco
# All rights reserved.
#
# This software is free for non-commercial, research and evaluation use
# under the terms of the LICENSE.md file.
#
# For inquiries contact  george.drettakis@inria.fr
#

cmake_minimum_required(VERSION 3.20)

project(DiffRast LANGUAGES CUDA CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CUDA_STANDARD 17)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

add_library(CudaRasterizer
        cuda_rasterizer/backward.h
        cuda_rasterizer/backward.cu
        cuda_rasterizer/forward.h
        cuda_rasterizer/forward.cu
        cuda_rasterizer/auxiliary.h
        cuda_rasterizer/rasterizer_impl.cu
        cuda_rasterizer/rasterizer_impl.h
        cuda_rasterizer/rasterizer.h
)
set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "native")
# set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "75;86")

target_include_directories(CudaRasterizer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/cuda_rasterizer) # CUDA 버전지정
target_include_directories(CudaRasterizer PRIVATE third_party/glm ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}) # CUDA 버전지정
```

<br>

### 1) CUDA 설정 추가
: conda 환경에 설치된 CUDA에 대한  환경변수를 등록하였다. `GaussianHeadAvatar`는 해당 가상환경 이름이다.
```js
export CUDA_HOME=~/miniconda3/envs/GaussianHeadAvatar/lib
export PATH=~/miniconda3/envs/GaussianHeadAvatar/bin:$PATH
export LD_LIBRARY_PATH=~/miniconda3/envs/GaussianHeadAvatar/lib:$LD_LIBRARY_PATH
```

### 2) Cmake 파일 수정
: cmake 파일을 수정하였다. `native`선언된 기존 아키텍처 선언은 명시화 하엿고, CUDA 경로도 직접 적어주었다.
```js
cmake_minimum_required(VERSION 3.20)

# 프로젝트 이름과 언어 설정
project(DiffRast LANGUAGES CUDA CXX)

# C++ 및 CUDA 표준 설정
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CUDA_STANDARD 17)

# 추가 플래그 (필요 시 수정)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# CUDA 경로 수동 설정 (가상환경 경로 지정)
set(CUDA_TOOLKIT_ROOT_DIR "~/miniconda3/envs/GaussianHeadAvatar/lib")
set(CMAKE_CUDA_COMPILER "~/miniconda3/envs/GaussianHeadAvatar/bin/nvcc")

# 라이브러리 추가
add_library(CudaRasterizer
    cuda_rasterizer/backward.h
    cuda_rasterizer/backward.cu
    cuda_rasterizer/forward.h
    cuda_rasterizer/forward.cu
    cuda_rasterizer/auxiliary.h
    cuda_rasterizer/rasterizer_impl.cu
    cuda_rasterizer/rasterizer_impl.h
    cuda_rasterizer/rasterizer.h
)

# CUDA 아키텍처 설정
set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "75;86")

# Include 디렉토리 추가
target_include_directories(CudaRasterizer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/cuda_rasterizer)
target_include_directories(CudaRasterizer PRIVATE third_party/glm ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})

# 디버깅 정보 출력
message(STATUS "CUDA Toolkit Root: ${CUDA_TOOLKIT_ROOT_DIR}")
message(STATUS "CUDA Compiler: ${CMAKE_CUDA_COMPILER}")
```

**Comment by oMFDOo** [comment]
### 페이즈 2 시작 새로운 오류의 반격
: 읽어보면 아래와 같다.

 - CUDA 경로 문제: nvcc 파일을 /home/azureuser/miniconda3/envs/GaussianHeadAvatar/lib/bin/에서 찾으려 하지만, 해당 경로에 파일이 없음
 - ninja 빌드 도구 누락: 빌드 과정에서 ninja를 사용하려고 했지만 설치되지 않아 distutils로 경고하라고 알려줌
 - setuptools 경고: setup.py 직접 실행하는 것이 방식이 옛날 방식임을 알려줌
 => ninja 설치하고 `which nvcc`를 통해 위치 알아내서 다시 써주자.

![Image](https://github.com/user-attachments/assets/5c625a10-4714-43a3-a3c7-7cff94f100c6)
```hing
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Processing ./submodules/diff-gaussian-rasterization
Building wheels for collected packages: diff-gaussian-rasterization
  Building wheel for diff-gaussian-rasterization (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-s09r1why
       cwd: /tmp/pip-req-build-8ursbdx9/
  Complete output (9 lines):
  running bdist_wheel
  /home/azureuser/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
  copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
  running build_ext
  error: [Errno 2] No such file or directory: '/home/azureuser/miniconda3/envs/GaussianHeadAvatar/lib/bin/nvcc'
  ----------------------------------------
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
Installing collected packages: diff-gaussian-rasterization
    Running setup.py install for diff-gaussian-rasterization ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n8uij5cv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/azureuser/.local/include/python3.8/diff-gaussian-rasterization
         cwd: /tmp/pip-req-build-8ursbdx9/
    Complete output (22 lines):
    running install
    /home/azureuser/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!

            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.

            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************

    !!
      self.initialize_options()
    running build
    running build_py
    creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
    copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
    running build_ext
    /home/azureuser/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py:495: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    error: [Errno 2] No such file or directory: '/home/azureuser/miniconda3/envs/GaussianHeadAvatar/lib/bin/nvcc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8ursbdx9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-n8uij5cv/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/azureuser/.local/include/python3.8/diff-gaussian-rasterization Check the logs for full command output.
```

**Comment by oMFDOo** [comment]
### 페이즈 2를 위한 노력

<br>

1) ninja 설치
```js
sudo apt install ninja-build
```
![Image](https://github.com/user-attachments/assets/1bb869c2-da11-41b7-83e8-ad4cd162c476)

<br>
2) CUDA toolkit 설치
: 생각해보니 cudatoolkit이 없었다... nvcc는 conda에 존재하지 않아서 외부에 설치해 사용해보고자 한다.
![Image](https://github.com/user-attachments/assets/19aa1880-41eb-40a9-bce7-b570151e672c)

```js
conda install -c nvidia cudatoolkit=11.7
```

3) 3차 CMake 수정
: 기존 cuda 경로는 그대로 두는데 nvcc 경로는 로컬파일에 진짜 설치된 위치로 했다. 위치는 `which nvcc`로 파악해 적었다.
```js
cmake_minimum_required(VERSION 3.20)

# 프로젝트 이름과 언어 설정
project(DiffRast LANGUAGES CUDA CXX)

# C++ 및 CUDA 표준 설정
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CUDA_STANDARD 17)

# 추가 플래그 (필요 시 수정)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# Conda 환경에서 CUDA 관련 경로 설정
set(CONDA_ENV_PATH "$ENV{CONDA_PREFIX}") # 현재 활성화된 Conda 환경 경로 가져오기
set(CUDA_TOOLKIT_ROOT_DIR "/usr")        # CUDA 설치 경로 (시스템 NVCC 사용)
set(CMAKE_CUDA_COMPILER "/usr/bin/nvcc") # 시스템 NVCC 사용

# Include 및 라이브러리 경로 설정
set(CUDA_INCLUDE_DIRS "${CONDA_ENV_PATH}/include")   # Conda 환경에서 제공되는 CUDA 헤더 경로
set(CUDA_LIBRARY_DIRS "${CONDA_ENV_PATH}/lib")       # Conda 환경에서 제공되는 CUDA 라이브러리 경로

# 라이브러리 추가
add_library(CudaRasterizer
    cuda_rasterizer/backward.h
    cuda_rasterizer/backward.cu
    cuda_rasterizer/forward.h
    cuda_rasterizer/forward.cu
    cuda_rasterizer/auxiliary.h
    cuda_rasterizer/rasterizer_impl.cu
    cuda_rasterizer/rasterizer_impl.h
    cuda_rasterizer/rasterizer.h
)

# CUDA 아키텍처 설정
set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "75;86")

# Include 디렉토리 추가
target_include_directories(CudaRasterizer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/cuda_rasterizer)
target_include_directories(CudaRasterizer PRIVATE 
    third_party/glm 
    ${CUDA_INCLUDE_DIRS}
)

# 라이브러리 디렉토리 설정
target_link_directories(CudaRasterizer PRIVATE ${CUDA_LIBRARY_DIRS})

# 디버깅 정보 출력
message(STATUS "Conda Environment Path: ${CONDA_ENV_PATH}")
message(STATUS "CUDA Toolkit Root: ${CUDA_TOOLKIT_ROOT_DIR}")
message(STATUS "CUDA Compiler: ${CMAKE_CUDA_COMPILER}")
message(STATUS "CUDA Include Dirs: ${CUDA_INCLUDE_DIRS}")
message(STATUS "CUDA Library Dirs: ${CUDA_LIBRARY_DIRS}")
```

**Comment by oMFDOo** [comment]
### 페이즈 3 시작
: cuda 경로 또 잘못 적었나보다... 위치를 상수로 적어봐야겠다...
![Image](https://github.com/user-attachments/assets/a78e3b0f-59b7-4760-9331-8a14b67ac41e)

**Comment by oMFDOo** [comment]
### 페이즈 3 해결을 위한 노력
: 나만 쓰는 가상머신이 아니기에 신중을 기울이고 있다... 혹여나 문제 생긴다면 나에게 연락이 오도록...

- 너무 안타까운 실수를 범했다 나는 지금 이 가상환경에서는 miniconda가 아니라 anaconda3를 쓰고 있었다...
- 경로를 anaconda3로 바꾸어주었다.

```sh
##### Edited by Hwang-Jinju #####
# Date : 2024.11.18
# Reason : Required for CUDA enviroment path

export PATH=/usr/bin:$PATH
export CUDA_HOME=/home/azureuser/anaconda3/envs/GaussianHeadAvatar
export LD_LIBRARY_PATH=/home/azureuser/anaconda3/envs/GaussianHeadAvatar/lib:$LD_LIBRARY_PATH

##### End of comments #####
```

**Comment by oMFDOo** [comment]
### 페이즈 4 돌입
: 이제 cuda 오류는 사라졌다. 

```sh
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-uzmj3458/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-uzmj3458/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-uzmj3458/pip-egg-info
         cwd: /tmp/pip-req-build-uzmj3458/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-uzmj3458/setup.py", line 13, in <module>
        from torch.utils.cpp_extension import CUDAExtension, BuildExtension
      File "/home/azureuser/.local/lib/python3.8/site-packages/torch/__init__.py", line 18, in <module>
        import ctypes
      File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_closure_alloc, version LIBFFI_CLOSURE_7.0
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
![Image](https://github.com/user-attachments/assets/d122ffc8-bd8d-48dd-9f93-85186f54fb72)

**Comment by oMFDOo** [comment]
### 페이즈 4를 위한 노력
: Python의 ctypes 모듈이 사용하는 libffi 라이브러리의 버전 불일치

<br>
libffi 라이브러리 업데이트

```bash
sudo apt-get update
sudo apt install --reinstall libffi-dev python3-dev
sudo apt install build-essential zlib1g-dev libffi-dev libssl-dev
```

**Comment by oMFDOo** [comment]
### 페이즈 5
: `_ctypes` 모듈과 `libffi` 라이브러리의 호환성 문제

```
/usr/bin/pip:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Processing /home/azureuser/GaussianHeadAvatar/2D-surfel-gaussian/submodules/diff-gaussian-rasterization
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0vv7foq_/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0vv7foq_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-0vv7foq_/pip-egg-info
         cwd: /tmp/pip-req-build-0vv7foq_/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0vv7foq_/setup.py", line 13, in <module>
        from torch.utils.cpp_extension import CUDAExtension, BuildExtension
      File "/home/azureuser/.local/lib/python3.8/site-packages/torch/__init__.py", line 18, in <module>
        import ctypes
      File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: ffi_closure_alloc, version LIBFFI_CLOSURE_7.0
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
![Image](https://github.com/user-attachments/assets/2c52c976-0b84-4aa4-ab1d-8481f893e4c5)

**Comment by oMFDOo** [comment]
# 해결

### 1) conda가 아닌 가상환경에 CUDA 12.6 버전 설치
 - [참고 블로그](https://freddiekim.tistory.com/6)
 - 설치 코드
```bash
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.2-560.35.03-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.2-560.35.03-1_amd64.deb
sudo cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-6
```

<br>

### 2) `~/.bashrc` 환경변수 재설정
: 기존 `conda` 내부의 cuda가 아닌 외부 12.6 버전으로 지정함
```bash
##### Edited by Hwang-Jinju #####
# Date : 2024.11.18
# Reason : Required for CUDA enviroment path
export PATH=/usr/local/cuda-12.6/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-12.6
##### End of comments #####
```

<br>

### 3) conda 가상환경 재생성 및 cuda 환경 추가 설치

```bash
conda create -n generate3d python=3.8 -y
conda activate generate3d
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
```

<br>

### 4) `pip install .` 실행
```bash
pip install .
```
![Image](https://github.com/user-attachments/assets/cc9ce411-4d55-4b90-8584-19ea23770174)

### + Cmake 파일
```js
cmake_minimum_required(VERSION 3.20)

# 프로젝트 이름과 언어 설정
project(DiffRast LANGUAGES CUDA CXX)

# C++ 및 CUDA 표준 설정
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CUDA_STANDARD 17)

# 추가 플래그 (필요 시 수정)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# Conda 환경에서 CUDA 관련 경로 설정
set(CONDA_ENV_PATH "$ENV{CONDA_PREFIX}") # 현재 활성화된 Conda 환경 경로 가져오기
set(CUDA_TOOLKIT_ROOT_DIR "/usr")        # CUDA 설치 경로 (시스템 NVCC 사용)
set(CMAKE_CUDA_COMPILER "/usr/bin/nvcc") # 시스템 NVCC 사용

# Include 및 라이브러리 경로 설정
set(CUDA_INCLUDE_DIRS "${CONDA_ENV_PATH}/include")   # Conda 환경에서 제공되는 CUDA 헤더 경로
set(CUDA_LIBRARY_DIRS "${CONDA_ENV_PATH}/lib")       # Conda 환경에서 제공되는 CUDA 라이브러리 경로

# 라이브러리 추가
add_library(CudaRasterizer
    cuda_rasterizer/backward.h
    cuda_rasterizer/backward.cu
    cuda_rasterizer/forward.h
    cuda_rasterizer/forward.cu
    cuda_rasterizer/auxiliary.h
    cuda_rasterizer/rasterizer_impl.cu
    cuda_rasterizer/rasterizer_impl.h
    cuda_rasterizer/rasterizer.h
)

# CUDA 아키텍처 설정
set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "75;86")

# Include 디렉토리 추가
target_include_directories(CudaRasterizer PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/cuda_rasterizer)
target_include_directories(CudaRasterizer PRIVATE
    third_party/glm
    ${CUDA_INCLUDE_DIRS}
)

# 라이브러리 디렉토리 설정
target_link_directories(CudaRasterizer PRIVATE ${CUDA_LIBRARY_DIRS})

# 디버깅 정보 출력
message(STATUS "Conda Environment Path: ${CONDA_ENV_PATH}")
message(STATUS "CUDA Toolkit Root: ${CUDA_TOOLKIT_ROOT_DIR}")
message(STATUS "CUDA Compiler: ${CMAKE_CUDA_COMPILER}")
message(STATUS "CUDA Include Dirs: ${CUDA_INCLUDE_DIRS}")
message(STATUS "CUDA Library Dirs: ${CUDA_LIBRARY_DIRS}")
```

**Comment by oMFDOo** [comment]
# simple-knn 설치

`simple_knn.cu` 파일에 `#include <float.h>` 코드 추가 후 `pip install .`

![Image](https://github.com/user-attachments/assets/9d2a0d34-77f6-4ec1-812b-4377da4cdba6)

**Comment by oMFDOo** [comment]
# tets_data.npz 파일 추가
: `/Gaussian-Head-Avatar/gaussian-splatting/assets` 경로에 ["tets_data.npz"](https://drive.google.com/file/d/1SMkp8v8bDyYxEdyq25jWnAX1zeQuAkNq/view?usp=drive_link) 파일 넣기
![Image](https://github.com/user-attachments/assets/28b6209f-7468-4634-92de-6e8077200e07)

**Comment by oMFDOo** [comment]
테스트 가능한 두 가지 코드 중 하나 구동에 성공하였다.
아래는 `train_meshhead.py`에 대한 구현 결과이다.

### 0000
![Image](https://github.com/user-attachments/assets/2e916df1-d48c-4d3e-979e-e7b024f9310d)

### 3000
![Image](https://github.com/user-attachments/assets/59ce2413-c58a-4da2-9f2f-63057ee68e4b)

### 6000
![Image](https://github.com/user-attachments/assets/fe3c928b-d5b0-4652-9f25-ccc10655bda8)

### 9000
![Image](https://github.com/user-attachments/assets/8dfa04ca-5c3b-443d-913d-36c10b587c34)

**Comment by oMFDOo** [comment]
### `train_gaussianhead.py` 구동 완료

![Image](https://github.com/user-attachments/assets/72a81f83-4834-4dc8-b1fa-6ef87aa5a553)
