### ISSUE TITLE
[Infra] NCCL 설치

### ISSUE THREAD

**Issue by oMFDOo** [oMFDOo/OpenSourceIssue#6]
#1 과정 중 에러
```bash
#실행 명령어 : python train_meshhead.py --config config/train_meshhead_N031.yaml
Traceback (most recent call last):
  File "train_meshhead.py", line 2, in <module>
    import torch
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
```
![Image](https://github.com/user-attachments/assets/ca87127c-1c04-4f0f-93c4-b1434e025ced)

**Comment by oMFDOo** [comment]
nccl은 [여기](https://developer.nvidia.com/nccl)서 설치 가능하다.
특이하게 로그인 및 약관 동의를 해야했다.
그렇게 하면 아래 주소를 받게 된다.

해당 소스를 긁어 사용할 것이라도 약관동의는 하고 사용하도록 하자.
![Image](https://github.com/user-attachments/assets/c6bdc67f-27bf-4c1e-82bc-71dfe092b112)

<br>

```sh
# Network Installer for Ubuntu24.04
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update

# Network Installer for Ubuntu22.04
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update

# Network Installer for Ubuntu20.04
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
```
: 나는 Ubuntu20.04이므로 해당 코드를 사용했다.
<br>
![Image](https://github.com/user-attachments/assets/e16127fc-1f98-434b-bb66-0ef4d306ae26)

**Comment by oMFDOo** [comment]
![Image](https://github.com/user-attachments/assets/eb978a8b-9205-4000-9bdf-f10a268af4d4)

<br>

### libnccl 설치
```
sudo apt install -y libnccl2 libnccl-dev
```
![Image](https://github.com/user-attachments/assets/59c79632-613a-4f1a-884a-0090047f3b27)

<br>

### libnccl 존재 여부 확인법
```
ls /usr/lib/x86_64-linux-gnu/ | grep libnccl
```
![Image](https://github.com/user-attachments/assets/a362918b-bc8c-4e99-8e70-df1c5348a0f9)

<br>

### 심볼릭 링크 생성
: 둘의 경로가 다른데 환경변수로 넣으면 기존의 `LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH`경로를 엉망으로 만들게 된다. <br>
그렇기에 심볼릭 링크로 연결해주었다.
```
ls /usr/lib/x86_64-linux-gnu/ | grep libnccl # 어떤 친구들이 있나 확인 후 모든 친구들에 대해 심볼릭링크를 연결해주었음
sudo ln -sf /usr/lib/x86_64-linux-gnu/libnccl.so /usr/local/cuda-12.6/targets/x86_64-linux/lib/libnccl.so
sudo ln -sf /usr/lib/x86_64-linux-gnu/libnccl.so.2 /usr/local/cuda-12.6/targets/x86_64-linux/lib/libnccl.so.2
sudo ln -sf /usr/lib/x86_64-linux-gnu/libnccl.so.2.23.4 /usr/local/cuda-12.6/targets/x86_64-linux/lib/libnccl.so.2.23.4
sudo ln -sf /usr/lib/x86_64-linux-gnu/libnccl_static.a /usr/local/cuda-12.6/targets/x86_64-linux/lib/libnccl_static.a
```
![Image](https://github.com/user-attachments/assets/12fb2688-9c31-4e6d-b221-8b5fe62900c8)
![Image](https://github.com/user-attachments/assets/77e2a5e4-7870-4d5e-aa1c-b5f65232486d)
