### ISSUE TITLE
[Infra] libtorch 결여

### ISSUE THREAD

**Issue by oMFDOo** [oMFDOo/OpenSourceIssue#7]
#1 과정 중 #6 해결 이후 에러

```sh
#  실행 코드 : python train_meshhead.py --config config/train_meshhead_N031.yaml
Traceback (most recent call last):
  File "train_meshhead.py", line 7, in <module>
    from lib.dataset.Dataset import MeshDataset
  File "/home/azureuser/GaussianHeadAvatar/Gaussian-Head-Avatar/lib/dataset/Dataset.py", line 12, in <module>
    from pytorch3d.renderer.cameras import look_at_view_transform
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
```
![Image](https://github.com/user-attachments/assets/5f57f057-bd12-40b4-936d-e1b8873d2fb7)

: 해당 오류는 torch3D가 존재하지 않아 발생한 문제인데, cuda 11.8이 최대 지원 버전이므로 나는 소스코드 빌드를 해야한다.

<br>

혹시나 싶어 PyTorch3D를 다시 설치 해봤으나 올바르게 동작하지 않는다.
```sh
pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu118_pyt200/download.html
```

**Comment by oMFDOo** [comment]
해당 문제에 대해 두 가지 방안을 세웠다.

<br>

### 1) Torch3D를 직접 소스코드 빌드하는 방안
     * 해당 방식은 코드 변경이 필요없어 더 간결한 방식이 예상되나 빌드의 어려움이 존재함
     * 추가적으로 KETI에서 비추천을 받은 렌더러이기에 이러한 어려움을 뚫고 빌드해야하나 고민임
### 2) nvdiffrast를 이용한 렌더링
     * 해당 방식은 KETI와의 방향성까지 맞추어 나갈 수 있는 좋은 방법이 될 수 있을 것 같음
     * 허나, 이런 방식에 대한 지식이 없는 상태에서 소스코드를 수정해가며 만들어 낼 수 있을 지 의문임

**Comment by oMFDOo** [comment]
[[Infra] #7 PyTorch 결여 1차대안 : PyTorch3D 소스코드 빌드 #8](https://github.com/oMFDOo/OpenSourceIssue/issues/8) 에서 `libtorch_cuda_cu.so`를 인식했음으로 `1) Torch3D를 직접 소스코드 빌드하는 방안`에 대해서는 해결함
