### ISSUE TITLE
[infra] torch._six 결여

### ISSUE THREAD

**Issue by oMFDOo** [oMFDOo/OpenSourceIssue#9]
#7 을 기반으로 하여 #8 에서 해결한 이후 생긴 새로운 오류이다.

```sh
# 실행 코드 python train_meshhead.py --config config/train_meshhead_N031.yaml
Traceback (most recent call last):
  File "train_meshhead.py", line 9, in <module>
    from lib.module.MeshHeadModule import MeshHeadModule
  File "/home/azureuser/GaussianHeadAvatar/Gaussian-Head-Avatar/lib/module/MeshHeadModule.py", line 4, in <module>
    import kaolin
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/kaolin/io/__init__.py", line 1, in <module>
    from . import dataset
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/kaolin/io/dataset.py", line 31, in <module>
    from  ..utils.testing import contained_torch_equal
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/kaolin/utils/__init__.py", line 1, in <module>
    from . import testing
  File "/home/azureuser/anaconda3/envs/generate3d/lib/python3.8/site-packages/kaolin/utils/testing.py", line 20, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'
```

### 발생 원인
 - torch._six는 PyTorch 1.9.0 이후로 제거된 모듈
 - 이 모듈을 참조하는 코드는 이전 버전의 PyTorch를 대상으로 작성된 것

### 해결책
 - 이전 종속 사용하는 코드 변경

**Comment by oMFDOo** [comment]
`train_meshhead.py`코드의 해당 부분에서 `PyTorch 1.9.0`를 사용할 것 같은 녀석을 탐색해보려 한다.
![Image](https://github.com/user-attachments/assets/eeb3d10c-fddf-4482-b6f1-40b29677d012)

### 체크리스트
- [x] lib.dataset.Dataset
- [x] lib.dataset.DataLoaderX
- [x] lib.module.MeshHeadModule
- [x] lib.module.CameraModule
- [x] lib.recorder.Recorder
- [x] lib.trainer.MeshHeadTrainer

**Comment by oMFDOo** [comment]
### kaolin 버전 업그레이드
: 뚜렷한 이유는 잘 모르겠으나 일단 오류에서는 kaolin의 호환성이 문제라고 하니 업그레이드 해본다.

```sh
pip uninstall kaolin
pip install kaolin --upgrade
```
![Image](https://github.com/user-attachments/assets/bef26ac7-455c-498f-a93b-63492ae7f827)

<br><br>

아직 존재하는 설치 오류 문제
![Image](https://github.com/user-attachments/assets/02eedc16-f2b9-48c4-a0d2-dea58b3b2c8c)

+ 검증용 코드
```
python -c "import kaolin; print(kaolin.__version__)"
```

**Comment by oMFDOo** [comment]
### 공식 kaolin 설치 가이드
https://kaolin.readthedocs.io/en/latest/notes/installation.html#quick-start-linux-windows

```
pip install kaolin==0.17.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.4.1_cu121.html
```

<br>

어김없이 다가온 미지원 최신버전
![Image](https://github.com/user-attachments/assets/21e0c24c-d9fe-408a-8638-da66626e7edd)

**Comment by oMFDOo** [comment]
파일 탐색 결과 정확한 kaolin 사용 지점이 짚어지지 않음
연관 라이브러리에서의 사용으로 추론
